# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: make deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Unit Tests
          command: make test

      - run:
          name: Linter
          command: make lint

      - run:
          name: Generate Test Coverage
          command: make coverage

      - run:
          name: Move test coverate to artifacts
          command: |
              mkdir coverage
              mv ./target/coverage/lcov.info coverage/

      - run:
          name: Check Dependencies
          command: make check-dependencies

      - run:
          name: Generate Distribution
          command: make build

      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          prefix: tests
