# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Unit Tests
          command: lein test

      - run:
          name: Generate Test Coverage
          command: make coverage

      - run:
          name: Generate Distribution
          command: lein uberjar



orbs:
  coveralls: coveralls/coveralls@1.0.4

  test-coverage:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - coveralls/upload:
          path_to_lcov: ./target/coverage/lcov.info
          flag_name: Seding Coverage to Coveralls

  workflows:
    main-build:
      jobs:
        - build
        - test-coverage:
            requires:
              - build
